// Generated by CoffeeScript 1.6.3
var Buffer, es, gutil, parse;

es = require('event-stream');

parse = require('ractive').parse;

gutil = require('gulp-util');

Buffer = require('buffer').Buffer;

module.exports = function(opt) {
  if (opt == null) {
    opt = {};
  }
  return es.through(function(file) {
    var data, dest, error, ext, options, str;
    if (file.isNull()) {
      return this.emit('data', file);
    }
    if (file.isStream()) {
      return this.emit('error', new Error('gulp-ractive: Streaming not supported'));
    }
    str = file.contents.toString('utf8');
    ext = opt.ext != null ? '.' + opt.ext : '.ract';
    dest = gutil.replaceExtension(file.path, ext);
    options = {
      preserveWhitespace: opt.preserveWhitespace != null ? !!opt.preserveWhitespace : false,
      sanitize: opt.sanitize != null ? opt.sanitize : false
    };
    try {
      data = parse(str, options);
    } catch (_error) {
      error = _error;
      return this.emit('error', new Error(error));
    }
    file.contents = new Buffer(data);
    file.path = dest;
    return this.emit('data', file);
  });
};
